### ISSUE TITLE
Problem running the latest desktop gui

### ISSUE THREAD

**Issue by misfit-mischief** [rupeshs/fastsdcpu#140]
I saw that in v24 an upscaler was added, I was excited to test but upon installation running the start.sh it kicked back an error in terminal. 

"This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem."

I have tried reinstalling but to no avail. 

I've only ran into this issue once before (with v22 on fedora) and just needed to install qt5-base-gui. This current issue is on xubuntu, and figured I just needed the proper qtgui pkg but cant seem to nail down which pkg I am missing. 

Overall I can work around not having the desktop gui since the webui works, but it does increase generation time since webui uses resources the desktop gui doesn't.

Also v23 desktop gui runs just fine on the same xubuntu machine. Just curious what change could cause this issue.

Lastly thanks for your time and effort on FastSD.

**Comment by rupeshs** [comment]
@misfit-mischief To use upscaler and other advanced features please use webui. To install without qt run
`./install.sh --disable-gui`

**Comment by monstruosoft** [comment]
I've run with this issue myself, it seems to be an issue with the Python package manager rather than with FastSD itself. Here's what I did, it might help you.
Set the environment variable _QT_DEBUG_PLUGINS_ as follows:

`export QT_DEBUG_PLUGINS=1`

In my case, the problem was Qt couldn't load the _libqxcb.so_ library. Since you mention that v23 works fine but v24 won't run, with Qt debugging enabled you might find that each version attempts to load that library from a different path. What I did was replace the problematic library with a copy of the one that's working. This worked for me, but keep the original file in case you have to revert the changes.

**Comment by misfit-mischief** [comment]
Yea, I'm using v23 desktop gui to gen and v24 to upscale, seems to work well that way for me. Thanks again.

**Comment by euneuber** [comment]
I'm also having this problem, maybe because my Linux distribution is supporting Qt5 *and* Qt6 and for both versions are those `libqxcb.so` libraries installed.

Since Qt is loaded via python 3.11.8, I have no clue which version is preferred and why this is not working (I'm not a python guy).

So **please** fix the Qt-gui-app !
